### ISSUE TITLE
k8s dashboard 安装 

### ISSUE THREAD

**Issue by liyann** [liyann/blog#25]
1. 部署dashboard
```sh
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
```
2. 启动代理
```sh
 kubectl proxy #默认8081
```
3. 通过特定地址打开url http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview?namespace=default
4. 创建一个admin-user账户
- 建立 dashboard-adminuser.yaml文件，内容如下
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
```
- 创建用户
```sh
kubectl apply -f dashboard-adminuser.yaml
```
5. 获取token
```sh
kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}') #获取token
```
6. 粘贴即可登录
![paste登录](https://user-images.githubusercontent.com/14969581/54469711-a5b22600-47d6-11e9-9964-78f1ebf80cbf.png)
